language: node_js
os: linux
node_js: lts/*
sudo: required
services:
- docker
cache:
  yarn: true
before_script:
- yarn
- yarn list
script:
- docker build .
after_success:
# travis-deploy-once is deprecated in favour of Travis Build Stages
# - yarn global add travis-deploy-once
# - travis-deploy-once "yarn semantic-release"
